fixtures:
  # use the forge modules so we can easily pin to a specific version
#  forge_modules:
#    stdlib: "puppetlabs/stdlib"
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
  symlinks:
    cobbler: "#{source_dir}"
